# Generated by Django 3.2.9 on 2021-11-08 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seniority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_name', models.CharField(max_length=100)),
                ('datetime_created', models.CharField(max_length=100)),
                ('agent_name', models.CharField(max_length=100)),
                ('agent_email', models.EmailField(max_length=254)),
                ('seniority_number', models.PositiveIntegerField()),
            ],
        ),
    ]
